# Generated by Django 4.1.5 on 2023-01-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('exam', models.CharField(max_length=255)),
                ('standard', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='papers/thumbnails')),
                ('pdf', models.FileField(upload_to='papers/pdf')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
