# Generated by Django 4.1.5 on 2023-01-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.CharField(choices=[('ENGLISH-1', 'ENGLISH-1'), ('ENGLISH-2', 'ENGLISH-2'), ('HINDI', 'HINDI'), ('BENGALI', 'BENGALI'), ('MATHS', 'MATHS'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGY', 'BIOLOGY'), ('COMPUTER', 'COMPUTER'), ('HISTORY', 'HISTORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('ECONOMICS', 'ECONOMICS'), ('POLITICAL SCIENCE', 'POLITICAL SCIENCE'), ('PSYCHOLOGY', 'PSYCHOLOGY'), ('PHILOSOPHY', 'PHILOSOPHY'), ('SANSKRIT', 'SANSKRIT'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('GK', 'GK')], default='ENGLISH-1', max_length=255),
        ),
    ]
