# Generated by Django 4.1.5 on 2023-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='standard',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
