# Generated by Django 4.1.5 on 2023-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='duration',
            field=models.IntegerField(default=7200000),
        ),
    ]
