# Generated by Django 4.1.5 on 2023-01-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_paper_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='duration',
        ),
    ]
