# Generated by Django 4.0.3 on 2022-10-27 07:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_transaction_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.CharField(default='ICSE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='city',
            field=models.CharField(default='Kolkata', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='institution',
            field=models.CharField(default='LMB', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.CharField(default='West Bengal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(blank=True, related_name='states', to='notes.city')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.ManyToManyField(blank=True, related_name='institutions', to='notes.note')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='cities', to='notes.institution'),
        ),
    ]
